/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Listing {
  'id' : bigint,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'seller' : Principal,
  'price' : bigint,
  'images' : Array<Uint8Array>,
}
export interface Property {
  'id' : bigint,
  'title' : string,
  'minimumInvestment' : bigint,
  'leaseStatus' : string,
  'targetYield' : number,
  'assetType' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phoneNumber' : string,
  'investorType' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WaitlistEntry {
  'name' : string,
  'email' : string,
  'timestamp' : Time,
  'phoneNumber' : string,
  'investorType' : [] | [string],
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createListing' : ActorMethod<
    [string, string, bigint, Array<Uint8Array>],
    bigint
  >,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedProperties' : ActorMethod<[], Array<Property>>,
  'getListingById' : ActorMethod<[bigint], [] | [Listing]>,
  'getListingsBySeller' : ActorMethod<[Principal], Array<Listing>>,
  'getPropertyById' : ActorMethod<[bigint], [] | [Property]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWaitlistEntries' : ActorMethod<[], Array<WaitlistEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinWaitlist' : ActorMethod<
    [string, string, string, [] | [string]],
    boolean
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];