/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'price' : IDL.Nat,
  'images' : IDL.Vec(IDL.Vec(IDL.Nat8)),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'investorType' : IDL.Opt(IDL.Text),
});
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'minimumInvestment' : IDL.Nat,
  'leaseStatus' : IDL.Text,
  'targetYield' : IDL.Float64,
  'assetType' : IDL.Text,
});
export const WaitlistEntry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'phoneNumber' : IDL.Text,
  'investorType' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Nat],
      [],
    ),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getListingById' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
  'getListingsBySeller' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getPropertyById' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWaitlistEntries' : IDL.Func([], [IDL.Vec(WaitlistEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinWaitlist' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'price' : IDL.Nat,
    'images' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'investorType' : IDL.Opt(IDL.Text),
  });
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'minimumInvestment' : IDL.Nat,
    'leaseStatus' : IDL.Text,
    'targetYield' : IDL.Float64,
    'assetType' : IDL.Text,
  });
  const WaitlistEntry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'phoneNumber' : IDL.Text,
    'investorType' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Nat],
        [],
      ),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getListingById' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
    'getListingsBySeller' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getPropertyById' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWaitlistEntries' : IDL.Func([], [IDL.Vec(WaitlistEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinWaitlist' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };